export const ANNOUNCEMENT_LIST_REQUEST = 'ANNOUNCEMENT_LIST_REQUEST'
export const ANNOUNCEMENT_LIST_SUCCESS = 'ANNOUNCEMENT_LIST_SUCCESS'
export const ANNOUNCEMENT_LIST_FAIL = 'ANNOUNCEMENT_LIST_FAIL'

export const ANNOUNCEMENT_CREATE_REQUEST = 'ANNOUNCEMENT_CREATE_REQUEST'
export const ANNOUNCEMENT_CREATE_SUCCESS = 'ANNOUNCEMENT_CREATE_SUCCESS'
export const ANNOUNCEMENT_CREATE_FAIL = 'ANNOUNCEMENT_CREATE_FAIL'
export const ANNOUNCEMENT_CREATE_RESET = 'ANNOUNCEMENT_CREATE_RESET'

export const ANNOUNCEMENT_ADMIN_REQUEST = 'ANNOUNCEMENT_ADMIN_REQUEST'
export const ANNOUNCEMENT_ADMIN_SUCCESS = 'ANNOUNCEMENT_ADMIN_SUCCESS'
export const ANNOUNCEMENT_ADMIN_FAIL = 'ANNOUNCEMENT_ADMIN_FAIL'

export const ANNOUNCEMENT_DELETE_REQUEST = 'ANNOUNCEMENT_DELETE_REQUEST'
export const ANNOUNCEMENT_DELETE_SUCCESS = 'ANNOUNCEMENT_DELETE_SUCCESS'
export const ANNOUNCEMENT_DELETE_FAIL = 'ANNOUNCEMENT_DELETE_FAIL'

export const ANNOUNCEMENT_UPDATE_REQUEST = 'ANNOUNCEMENT_UPDATE_REQUEST'
export const ANNOUNCEMENT_UPDATE_SUCCESS = 'ANNOUNCEMENT_UPDATE_SUCCESS'
export const ANNOUNCEMENT_UPDATE_FAIL = 'ANNOUNCEMENT_UPDATE_FAIL'
export const ANNOUNCEMENT_UPDATE_RESET = 'ANNOUNCEMENT_UPDATE_RESET'