export const APPLICATION_ORDER_REQUEST = 'APPLICATION_ORDER_REQUEST'
export const APPLICATION_ORDER_SUCCESS = 'APPLICATION_ORDER_SUCCESS'
export const APPLICATION_ORDER_FAIL = 'APPLICATION_ORDER_FAIL'
export const APPLICATION_ORDER_RESET = 'APPLICATION_ORDER_RESET'

export const APPLICATION_DETAILS_REQUEST = 'APPLICATION_DETAILS_REQUEST'
export const APPLICATION_DETAILS_SUCCESS = 'APPLICATION_DETAILS_SUCCESS'
export const APPLICATION_DETAILS_FAIL = 'APPLICATION_DETAILS_FAIL'
export const APPLICATION_DETAILS_RESET = 'APPLICATION_DETAILS_RESET'

export const APPLICATION_BYID_REQUEST = 'APPLICATION_BYID_REQUEST'
export const APPLICATION_BYID_SUCCESS = 'APPLICATION_BYID_SUCCESS'
export const APPLICATION_BYID_FAIL = 'APPLICATION_BYID_FAIL'
export const APPLICATION_BYID_RESET = 'APPLICATION_BYID_RESET'

export const ALL_APPLICATION_REQUEST = 'ALL_APPLICATION_REQUEST'
export const ALL_APPLICATION_SUCCESS = 'ALL_APPLICATION_SUCCESS'
export const ALL_APPLICATION_FAIL = 'ALL_APPLICATION_FAIL'

export const APPLICATION_UPDATE_REQUEST = 'APPLICATION_UPDATE_REQUEST'
export const APPLICATION_UPDATE_SUCCESS = 'APPLICATION_UPDATE_SUCCESS'
export const APPLICATION_UPDATE_FAIL = 'APPLICATION_UPDATE_FAIL'
export const APPLICATION_UPDATE_RESET = 'APPLICATION_UPDATE_RESET'

export const APPLICATION_DELETE_REQUEST = 'APPLICATION_DELETE_REQUEST'
export const APPLICATION_DELETE_SUCCESS = 'APPLICATION_DELETE_SUCCESS'
export const APPLICATION_DELETE_FAIL = 'APPLICATION_DELETE_FAIL'
export const APPLICATION_DELETE_RESET = 'APPLICATION_DELETE_RESET'

export const APPLICATION_TEACHER_REQUEST = 'APPLICATION_TEACHER_REQUEST'
export const APPLICATION_TEACHER_SUCCESS = 'APPLICATION_TEACHER_SUCCESS'
export const APPLICATION_TEACHER_FAIL = 'APPLICATION_TEACHER_FAIL'

export const COUNT_ONGOING_REQUEST = 'COUNT_ONGOING_REQUEST'
export const COUNT_ONGOING_SUCCESS = 'COUNT_ONGOING_SUCCESS'
export const COUNT_ONGOING_FAIL = 'COUNT_ONGOING_FAIL'

export const COUNT_FINISHED_REQUEST = 'COUNT_FINISHED_REQUEST'
export const COUNT_FINISHED_SUCCESS = 'COUNT_FINISHED_SUCCESS'
export const COUNT_FINISHED_FAIL = 'COUNT_FINISHED_FAIL'

export const COUNT_ENROLL_STUDENT_REQUEST = 'COUNT_ENROLL_STUDENT_REQUEST'
export const COUNT_ENROLL_STUDENT_SUCCESS = 'COUNT_ENROLL_STUDENT_SUCCESS'
export const COUNT_ENROLL_STUDENT_FAIL = 'COUNT_ENROLL_STUDENT_FAIL'