export const EXAM_LIST_REQUEST = 'EXAM_LIST_REQUEST'
export const EXAM_LIST_SUCCESS = 'EXAM_LIST_SUCCESS'
export const EXAM_LIST_FAIL = 'EXAM_LIST_FAIL'

export const GET_SINGLE_EXAM_REQUEST = 'GET_SINGLE_EXAM_REQUEST'
export const GET_SINGLE_EXAM_SUCCESS = 'GET_SINGLE_EXAM_SUCCESS'
export const GET_SINGLE_EXAM_FAIL = 'GET_SINGLE_EXAM_FAIL'
export const GET_SINGLE_EXAM_RESET = 'GET_SINGLE_EXAM_RESET'

export const CREATE_EXAM_REQUEST = 'CREATE_EXAM_REQUEST'
export const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS'
export const CREATE_EXAM_FAIL = 'CREATE_EXAM_FAIL'
export const CREATE_EXAM_RESET = 'CREATE_EXAM_RESET'

export const DELETE_EXAM_REQUEST = 'DELETE_EXAM_REQUEST'
export const DELETE_EXAM_SUCCESS = 'DELETE_EXAM_SUCCESS'
export const DELETE_EXAM_FAIL = 'DELETE_EXAM_FAIL'
export const DELETE_EXAM_RESET = 'DELETE_EXAM_RESET'

export const PUBLIC_EXAM_LIST_REQUEST = 'PUBLIC_EXAM_LIST_REQUEST'
export const PUBLIC_EXAM_LIST_SUCCESS = 'PUBLIC_EXAM_LIST_SUCCESS'
export const PUBLIC_EXAM_LIST_FAIL = 'PUBLIC_EXAM_LIST_FAIL'

export const CREATE_EXAM_PUBLIC_REQUEST = 'CREATE_EXAM_PUBLIC_REQUEST'
export const CREATE_EXAM_PUBLIC_SUCCESS = 'CREATE_EXAM_PUBLIC_SUCCESS'
export const CREATE_EXAM_PUBLIC_FAIL = 'CREATE_EXAM_PUBLIC_FAIL'
export const CREATE_EXAM_PUBLIC_RESET = 'CREATE_EXAM_PUBLIC_RESET'