export const LESSONS_DETAILS_REQUEST = 'LESSONS_DETAILS_REQUEST'
export const LESSONS_DETAILS_SUCCESS = 'LESSONS_DETAILS_SUCCESS'
export const LESSONS_DETAILS_FAIL = 'LESSONS_DETAILS_FAIL'
export const LESSONS_DETAILS_RESET = 'LESSONS_DETAILS_RESET'

export const LESSONS_CREATE_REQUEST = 'LESSONS_CREATE_REQUEST'
export const LESSONS_CREATE_SUCCESS = 'LESSONS_CREATE_SUCCESS'
export const LESSONS_CREATE_FAIL = 'LESSONS_CREATE_FAIL'
export const LESSONS_CREATE_RESET = 'LESSONS_CREATE_RESET'

export const LESSON_DETAILS_REQUEST = 'LESSON_DETAILS_REQUEST'
export const LESSON_DETAILS_SUCCESS = 'LESSON_DETAILS_SUCCESS'
export const LESSON_DETAILS_FAIL = 'LESSON_DETAILS_FAIL'
export const LESSON_DETAILS_RESET = 'LESSON_DETAILS_RESET'

export const LESSON_DELETE_REQUEST = 'LESSON_DELETE_REQUEST'
export const LESSON_DELETE_SUCCESS = 'LESSON_DELETE_SUCCESS'
export const LESSON_DELETE_FAIL = 'LESSON_DELETE_FAIL'

export const LESSON_UPDATE_REQUEST = 'LESSON_UPDATE_REQUEST'
export const LESSON_UPDATE_SUCCESS = 'LESSON_UPDATE_SUCCESS'
export const LESSON_UPDATE_FAIL = 'LESSON_UPDATE_FAIL'
export const LESSON_UPDATE_RESET = 'LESSON_UPDATE_RESET'

export const LESSON_UPDATE_NEW_REQUEST = 'LESSON_UPDATE_NEW_REQUEST'
export const LESSON_UPDATE_NEW_SUCCESS = 'LESSON_UPDATE_NEW_SUCCESS'
export const LESSON_UPDATE_NEW_FAIL = 'LESSON_UPDATE_NEW_FAIL'
export const LESSON_UPDATE_NEW_RESET = 'LESSON_UPDATE_NEW_RESET'


export const LESSON_TIME_REQUEST = 'LESSON_TIME_REQUEST'
export const LESSON_TIME_SUCCESS = 'LESSON_TIME_SUCCESS'
export const LESSON_TIME_FAIL = 'LESSON_TIME_FAIL'
export const LESSON_TIME_RESET = 'LESSON_TIME_RESET'


export const FINISHED_LESSON_REQUEST = 'FINISHED_LESSON_REQUEST'
export const FINISHED_LESSON_SUCCESS = 'FINISHED_LESSON_SUCCESS'
export const FINISHED_LESSON_FAIL = 'FINISHED_LESSON_FAIL'

export const ONGOING_LESSON_REQUEST = 'ONGOING_LESSON_REQUEST'
export const ONGOING_LESSON_SUCCESS = 'ONGOING_LESSON_SUCCESS'
export const ONGOING_LESSON_FAIL = 'ONGOING_LESSON_FAIL'

export const GETNEW_LESSON_REQUEST = 'GETNEW_LESSON_REQUEST'
export const GETNEW_LESSON_SUCCESS = 'GETNEW_LESSON_SUCCESS'
export const GETNEW_LESSON_FAIL = 'GETNEW_LESSON_FAIL'

export const COUNT_STUDENT_LESSON_REQUEST = 'COUNT_STUDENT_LESSON_REQUEST'
export const COUNT_STUDENT_LESSON_SUCCESS = 'COUNT_STUDENT_LESSON_SUCCESS'
export const COUNT_STUDENT_LESSON_FAIL = 'COUNT_STUDENT_LESSON_FAIL'

export const CREATE_NOTES_REQUEST = 'CREATE_NOTES_REQUEST'
export const CREATE_NOTES_SUCCESS = 'CREATE_NOTES_SUCCESS'
export const CREATE_NOTES_FAIL = 'CREATE_NOTES_FAIL'
export const CREATE_NOTES_RESET = 'CREATE_NOTES_RESET'
