export const LIBRARY_LIST_REQUEST = 'LIBRARY_LIST_REQUEST'
export const LIBRARY_LIST_SUCCESS = 'LIBRARY_LIST_SUCCESS'
export const LIBRARY_LIST_FAIL = 'LIBRARY_LIST_FAIL'

export const LIBRARY_LIMIT_REQUEST = 'LIBRARY_LIMIT_REQUEST'
export const LIBRARY_LIMIT_SUCCESS = 'LIBRARY_LIMIT_SUCCESS'
export const LIBRARY_LIMIT_FAIL = 'LIBRARY_LIMIT_FAIL'