export const POINTS_LIST_REQUEST = 'POINTS_LIST_REQUEST'
export const POINTS_LIST_SUCCESS = 'POINTS_LIST_SUCCESS'
export const POINTS_LIST_FAIL = 'POINTS_LIST_FAIL'

export const CREATE_POINTS_REQUEST = 'CREATE_POINTS_REQUEST'
export const CREATE_POINTS_SUCCESS = 'CREATE_POINTS_SUCCESS'
export const CREATE_POINTS_FAIL = 'CREATE_POINTS_FAIL'
export const CREATE_POINTS_RESET = 'CREATE_POINTS_RESET'

export const DELETE_POINTS_REQUEST = 'DELETE_POINTS_REQUEST'
export const DELETE_POINTS_SUCCESS = 'DELETE_POINTS_SUCCESS'
export const DELETE_POINTS_FAIL = 'DELETE_POINTS_FAIL'

export const STUDENT_POINTS_REQUEST = 'STUDENT_POINTS_REQUEST'
export const STUDENT_POINTS_SUCCESS = 'STUDENT_POINTS_SUCCESS'
export const STUDENT_POINTS_FAIL = 'STUDENT_POINTS_FAIL'
export const STUDENT_POINTS_RESET = 'STUDENT_POINTS_RESET'