export const PURCHASED_CLASS_REQUEST = 'PURCHASED_CLASS_REQUEST'
export const PURCHASED_CLASS_SUCCESS = 'PURCHASED_CLASS_SUCCESS'
export const PURCHASED_CLASS_FAIL = 'PURCHASED_CLASS_FAIL'

export const PURCHASED_CREATEUPDATE_REQUEST = 'PURCHASED_CREATEUPDATE_REQUEST'
export const PURCHASED_CREATEUPDATE_SUCCESS = 'PURCHASED_CREATEUPDATE_SUCCESS'
export const PURCHASED_CREATEUPDATE_FAIL = 'PURCHASED_CREATEUPDATE_FAIL'
export const PURCHASED_CREATEUPDATE_RESET = 'PURCHASED_CREATEUPDATE_RESET'

export const PURCHASED_DELETE_REQUEST = 'PURCHASED_DELETE_REQUEST'
export const PURCHASED_DELETE_SUCCESS = 'PURCHASED_DELETE_SUCCESS'
export const PURCHASED_DELETE_FAIL = 'PURCHASED_DELETE_FAIL'

export const PURCHASED_CLASS_BYID_REQUEST = 'PURCHASED_CLASS_BYID_REQUEST'
export const PURCHASED_CLASS_BYID_SUCCESS = 'PURCHASED_CLASS_BYID_SUCCESS'
export const PURCHASED_CLASS_BYID_FAIL = 'PURCHASED_CLASS_BYID_FAIL'