export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL'
export const USER_REGISTRATION_RESET = 'USER_REGISTRATION_RESET'

export const COMPLETE_REG_REQUEST = 'COMPLETE_REG_REQUEST'
export const COMPLETE_REG_SUCCESS = 'COMPLETE_REG_SUCCESS'
export const COMPLETE_REG_FAIL = 'COMPLETE_REG_FAIL'
export const COMPLETE_REG_RESET = 'COMPLETE_REG_RESET'


export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const TEACHER_REQUEST = 'TEACHER_REQUEST'
export const TEACHER_FAIL = 'TEACHER_FAIL'
export const TEACHER_SUCCESS = 'TEACHER_SUCCESS'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'

export const CHECK_USER_DETAILS_REQUEST = 'CHECK_USER_DETAILS_REQUEST'
export const CHECK_USER_DETAILS_FAIL = 'CHECK_USER_DETAILS_FAIL'
export const CHECK_USER_DETAILS_SUCCESS = 'CHECK_USER_DETAILS_SUCCESS'
export const CHECK_USER_DETAILS_RESET = 'CHECK_USER_DETAILS_RESET'

export const UPDATE_USER_PHOTO_REQUEST = 'UPDATE_USER_PHOTO_REQUEST'
export const UPDATE_USER_PHOTO_FAIL = 'UPDATE_USER_PHOTO_FAIL'
export const UPDATE_USER_PHOTO_SUCCESS = 'UPDATE_USER_PHOTO_SUCCESS'
export const UPDATE_USER_PHOTO_RESET = 'UPDATE_USER_PHOTO_RESET'

export const UPDATE_USER_IMAGE_REQUEST = 'UPDATE_USER_IMAGE_REQUEST'
export const UPDATE_USER_IMAGE_FAIL = 'UPDATE_USER_IMAGE_FAIL'
export const UPDATE_USER_IMAGE_SUCCESS = 'UPDATE_USER_IMAGE_SUCCESS'
