export const VIDEOS_REQUEST = 'VIDEOS_REQUEST'
export const VIDEOS_SUCCESS = 'VIDEOS_SUCCESS'
export const VIDEOS_FAIL = 'VIDEOS_FAIL'

export const CREATE_VIDEO_REQUEST = 'CREATE_VIDEO_REQUEST'
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS'
export const CREATE_VIDEO_FAIL = 'CREATE_VIDEO_FAIL'
export const CREATE_VIDEO_RESET = 'CREATE_VIDEO_RESET'

export const DELETE_VIDEO_REQUEST = 'DELETE_VIDEO_REQUEST'
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS'
export const DELETE_VIDEO_FAIL = 'DELETE_VIDEO_FAIL'

